# pulling offical image
FROM sonatype/nexus3

COPY nexus.properties nexus-data/etc/nexus.properties
COPY nexus3-keycloak-plugin-0.4.0-bundle.kar /opt/sonatype/nexus/deploy/nexus3-keycloak-plugin-0.4.0-bundle.kar