/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Environment in the datacenter
type Environment struct {

	// Unique environment ID
	Id int32 `json:"id,omitempty"`

	// Name of environment
	Name string `json:"name"`

	// Description of Environment
	Description string `json:"description,omitempty"`

	// Name of the contract
	Party string `json:"party,omitempty"`

	// Name of the App-PoD
	Pod string `json:"pod,omitempty"`

	// subnet
	Subnet string `json:"subnet,omitempty"`

	// subnet in bits
	Mask string `json:"mask,omitempty"`

	// Number of Servers
	Nos int32 `json:"nos,omitempty"`

	// Status of environment
	Status string `json:"status"`
}
