/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Tenant in the datacenter
type Tenant struct {

	// Unique tenant ID
	Id int32 `json:"id,omitempty"`

	// Name of tenant
	Name string `json:"name"`

	// Description of tenant
	Description string `json:"description,omitempty"`

	// Name of the contract
	Party string `json:"party"`

	// Status of tenant
	Status string `json:"status,omitempty"`
}
