/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Error response media type (default view)
type ModelError struct {

	// an application-specific error code, expressed as a string value.
	Code string `json:"code,omitempty"`

	// a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`

	// a unique identifier for this particular occurrence of the problem.
	Id string `json:"id,omitempty"`

	// a meta object containing non-standard meta-information about the error.
	Meta interface{} `json:"meta,omitempty"`

	// the HTTP status code applicable to this problem, expressed as a string value.
	Status string `json:"status,omitempty"`
}
