/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Server in the datacenter
type Server struct {

	// Unique server ID
	Id int32 `json:"id,omitempty"`

	// Name of server
	Name string `json:"name"`

	// Description of Server
	Description string `json:"description,omitempty"`

	// Name of the contract
	Party string `json:"party,omitempty"`

	// Name of the Environment
	Env string `json:"env,omitempty"`

	// Grootte of the server
	Size string `json:"size,omitempty"`

	// The ID of the OS
	Image int32 `json:"image,omitempty"`

	// Status of server
	Status string `json:"status"`
}
