/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Application in the datacenter
type Application struct {

	// Unique application ID
	Id int32 `json:"id,omitempty"`

	// Name of application
	Name string `json:"name"`

	// Description of Application
	Description string `json:"description,omitempty"`

	// Name of the contract
	Party string `json:"party,omitempty"`

	// Name of the App-PoD
	Pod string `json:"pod,omitempty"`

	// Status of application
	Status string `json:"status"`
}
