/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v001/",
		Index,
	},

	Route{
		"AddApplication",
		strings.ToUpper("Post"),
		"/v001/applications/",
		AddApplication,
	},

	Route{
		"DeleteApplication",
		strings.ToUpper("Delete"),
		"/v001/applications/{id}",
		DeleteApplication,
	},

	Route{
		"GetApplicationById",
		strings.ToUpper("Get"),
		"/v001/applications/{id}",
		GetApplicationById,
	},

	Route{
		"UpdateApplication",
		strings.ToUpper("Put"),
		"/v001/applications/",
		UpdateApplication,
	},

	Route{
		"UpdateApplicationWithForm",
		strings.ToUpper("Post"),
		"/v001/applications/{id}",
		UpdateApplicationWithForm,
	},

	Route{
		"AddAZ",
		strings.ToUpper("Post"),
		"/v001/azs/",
		AddAZ,
	},

	Route{
		"DeleteAZ",
		strings.ToUpper("Delete"),
		"/v001/azs/{id}",
		DeleteAZ,
	},

	Route{
		"GetAZById",
		strings.ToUpper("Get"),
		"/v001/azs/{id}",
		GetAZById,
	},

	Route{
		"UpdateAZ",
		strings.ToUpper("Put"),
		"/v001/azs/",
		UpdateAZ,
	},

	Route{
		"UpdateAZWithForm",
		strings.ToUpper("Post"),
		"/v001/azs/{id}",
		UpdateAZWithForm,
	},

	Route{
		"AddEnvironment",
		strings.ToUpper("Post"),
		"/v001/environments/",
		AddEnvironment,
	},

	Route{
		"DeleteEnvironment",
		strings.ToUpper("Delete"),
		"/v001/environments/{id}",
		DeleteEnvironment,
	},

	Route{
		"GetEnvironmentById",
		strings.ToUpper("Get"),
		"/v001/environments/{id}",
		GetEnvironmentById,
	},

	Route{
		"UpdateEnvironment",
		strings.ToUpper("Put"),
		"/v001/environments/",
		UpdateEnvironment,
	},

	Route{
		"UpdateEnvironmentWithForm",
		strings.ToUpper("Post"),
		"/v001/environments/{id}",
		UpdateEnvironmentWithForm,
	},

	Route{
		"AddImage",
		strings.ToUpper("Post"),
		"/v001/images/",
		AddImage,
	},

	Route{
		"AddPfImage",
		strings.ToUpper("Post"),
		"/v001/pf-images/",
		AddPfImage,
	},

	Route{
		"DeleteImage",
		strings.ToUpper("Delete"),
		"/v001/images/{id}",
		DeleteImage,
	},

	Route{
		"GetImageById",
		strings.ToUpper("Get"),
		"/v001/images/{id}",
		GetImageById,
	},

	Route{
		"GetPfImageById",
		strings.ToUpper("Get"),
		"/v001/pf-images/{id}",
		GetPfImageById,
	},

	Route{
		"UpdateImage",
		strings.ToUpper("Put"),
		"/v001/images/",
		UpdateImage,
	},

	Route{
		"UpdateImageWithForm",
		strings.ToUpper("Post"),
		"/v001/images/{id}",
		UpdateImageWithForm,
	},

	Route{
		"AddServer",
		strings.ToUpper("Post"),
		"/v001/servers/",
		AddServer,
	},

	Route{
		"DeleteServer",
		strings.ToUpper("Delete"),
		"/v001/servers/{id}",
		DeleteServer,
	},

	Route{
		"GetServerById",
		strings.ToUpper("Get"),
		"/v001/servers/{id}",
		GetServerById,
	},

	Route{
		"UpdateServer",
		strings.ToUpper("Put"),
		"/v001/servers/",
		UpdateServer,
	},

	Route{
		"UpdateServerWithForm",
		strings.ToUpper("Post"),
		"/v001/servers/{id}",
		UpdateServerWithForm,
	},

	Route{
		"AddTenant",
		strings.ToUpper("Post"),
		"/v001/tenants/",
		AddTenant,
	},

	Route{
		"DeleteTenant",
		strings.ToUpper("Delete"),
		"/v001/tenants/{id}",
		DeleteTenant,
	},

	Route{
		"GetTenantById",
		strings.ToUpper("Get"),
		"/v001/tenants/{id}",
		GetTenantById,
	},

	Route{
		"UpdateTenant",
		strings.ToUpper("Put"),
		"/v001/tenants/",
		UpdateTenant,
	},

	Route{
		"UpdateTenantWithForm",
		strings.ToUpper("Post"),
		"/v001/tenants/{id}",
		UpdateTenantWithForm,
	},
}
