FROM nitnelave/lldap:stable

USER lldap
ADD data/users.db /data/users.db
ADD data/users.db-shm /data/users.db-shm
ADD data/users.db-wal /data/users.db-wal
ADD data/lldap_config.toml /data/lldap_config.toml
