apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-deployment-template
  title: Application Deployment
  description: Creates a complete application development
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: You are about to create an application environment setup from a scaffolder
      required:
        - application-name
        - environment-name
      properties:
        application-name:
          type: string
        environment-name:
          type: string

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.name }}!'

