version: '3.8'
networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.9.0/24
  services:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
  tooling:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24
  reverse-proxy: null
  delivery:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.12.0/24
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.13.0/24
  management:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.14.0/24


volumes:
  cicdtoolbox_db_data: null
  cicdtoolbox_db_conf: null
  gitea:
    driver: local
  jenkins_certs: null
  jenkins_data: null
  jenkins_conf: null
  nexus_work: null
  nexus_db: null
  freeipa: null
  portainer_data: null
  sonarqube_data: null
  sonarqube_extensions: null
  sonarqube_logs: null
  sonarqube_temp: null

secrets:
  ca_crt:
    file: ./ca.crt
  keycloak_key:
    file: ./freeipa/certs/keycloak.services.provider.test.key
  keycloak_crt:
    file: ./freeipa/certs/keycloak.services.provider.test.pem
  jenkins_key:
    file: ./freeipa/certs/jenkins.tooling.provider.test.key
  jenkins_crt:
    file: ./freeipa/certs/jenkins.tooling.provider.test.pem
  nexus_key:
    file: ./freeipa/certs/nexus.tooling.provider.test.key
  nexus_crt:
    file: ./freeipa/certs/nexus.tooling.provider.test.pem

services:
  cicdtoolbox-db:
    container_name: cicdtoolbox-db.tooling.provider.test
    build: cicdtoolbox-db
    command: >
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - 'POSTGRES_MULTIPLE_DATABASES=gitea,keycloak,sonar,myreference'
      - POSTGRES_USER=netcicd
      - POSTGRES_PASSWORD=netcicd
    networks:
      internal:
        ipv4_address: 172.16.9.2
    expose:
      - '5432'
    volumes:
      - 'cicdtoolbox_db_data:/var/lib/postgresql/data'
      - 'cicdtoolbox_db_conf:/etc/postgresql'
      - './cicdtoolbox-db/docker-entrypoint-initdb-resources:/docker-entrypoint-initdb-resources:ro'

  keycloak.services.provider.test:
    container_name: keycloak.services.provider.test
    build: keycloak
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: cicdtoolbox-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: local-admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      JDBC_PARAMS: 'ssl=true&sslmode=verify-ca&sslrootcert=/etc/pki/ca-trust/source/anchors/ca.crt'
    secrets:
      - source: keycloak_key
        target: /etc/x509/https/tls.key
      - source: keycloak_crt
        target: /etc/x509/https/tls.crt
    networks:
      services:
        ipv4_address: 172.16.10.11
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - cicdtoolbox-db
    healthcheck:
      test: curl --insecure --head --fail -s https://localhost:8443 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  freeipa.services.provider.test:
    container_name: freeipa.services.provider.test
    build: freeipa
    restart: unless-stopped
    hostname: freeipa
    domainname: provider.test
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - 'freeipa:/data:Z'
    expose:
      - '80'
      - '443'
      - '389'
      - '636'
      - '88'
      - '464'
      - 88/udp
      - 464/udp
      - 123/udp
    environment:
      - IPA_SERVER_HOSTNAME=freeipa.services.provider.test
      - IPA_SERVER_INSTALL_OPTS=-d -r provider.test --ntp-pool=pool.ntp.org --domain=provider.test --reverse-zone=16.172.in-addr.arpa -p Pa55w0rd -a Pa55w0rd --no-host-dns --setup-dns --no-forwarders --ip-address 172.16.10.12 --pki-config-override=/etc/pki/pki.conf -U
      - IPA_SERVER_IP=172.16.10.12
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=freeipa.services.provider.test
      - VIRTUAL_PORT=80
    dns:
      - 127.0.0.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      services:
        ipv4_address: 172.16.10.12
      reverse-proxy: null
    healthcheck:
      test: curl --insecure --head --fail -s https://localhost || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  gitea.tooling.provider.test:
    container_name: gitea.tooling.provider.test
    build: gitea
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=gitea.tooling.provider.test
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    secrets:
      - source: ca_crt
        target: /usr/local/share/ca-certificates/CICD-toolbox-ca.crt
    networks:
      tooling:
        ipv4_address: 172.16.11.3
    volumes:
      - 'gitea:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    expose:
      - '3000'
    depends_on:
      - cicdtoolbox-db
      - keycloak.tooling.provider.test
    healthcheck:
      test: curl --insecure --head --fail -s https://localhost:3000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  jenkins.tooling.provider.test:
    container_name: jenkins.tooling.provider.test
    build: ./jenkins
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      tooling:
        ipv4_address: 172.16.11.8
    environment:
      - JENKINS_ADMIN_ID=local-admin
      - JENKINS_ADMIN_PASSWORD=netcicd
      - NETCICD_PASSWORD=netcicd
      - CML_USER=developer
      - CML_PASSWORD=C1sco12345
      - 'CML_URL=https://10.10.20.161'
      - GITEA_IP=172.16.11.3
      - JENKINS_IP=172.16.11.8
      - NEXUS_IP=172.16.11.9
      - JENKINS_JENKINS_PASSWORD=netcicd
      - JENKINS_NEXUS_PASSWORD=netcicd
      - JENKINS_ARGOS_PASSWORD=netcicd
    secrets:
      - source: jenkins_key
        target: /var/jenkins_home/jenkins.tooling.provider.test.key
      - source: jenkins_crt
        target: /var/jenkins_home/jenkins.tooling.provider.test.pem
    volumes:
      - 'jenkins_certs:/certs/client'
      - 'jenkins_data:/var/jenkins_home'
      - 'jenkins_conf:/var/jenkins_conf'
    ports:
      - '8084:8084'   
      - '50000:50000'
    depends_on:
      - keycloak.tooling.provider.test
    healthcheck:
      test: curl --insecure --head --fail -s https://localhost:8084/whoAmI || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  nexus.tooling.provider.test:
    container_name: nexus.tooling.provider.test
    build: nexus
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    user: nexus
    environment:
      BASE_URL: 'https://nexus.tooling.provider.test:8443'
      NEXUS_SECURITY_RANDOMPASSWORD: 'true'
      NEXUS_CASC_CONFIG: /opt/nexus.yaml
    secrets:
      - source: ca_crt
        target: /nexus-data/etc/ssl/ca.crt
    volumes:
      - 'nexus_work:/sonatype-work'
      - 'nexus_db:/nexus-data'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      tooling:
        ipv4_address: 172.16.11.9
    ports:
      - '8081:8081'
    healthcheck:
      test: curl --insecure --head --fail -s https://localhost:8443 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  build-dev.delivery.provider.test:
    container_name: build-dev.delivery.provider.test
    build: jenkins_buildnode
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    expose:
      - '50000'
    networks:
      delivery:
        ipv4_address: 172.16.12.2

  build-test.delivery.provider.test:
    container_name: build-test.delivery.provider.test
    build: jenkins_buildnode
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    expose:
      - '50000'
    networks:
      delivery:
        ipv4_address: 172.16.12.3

  build-acc.delivery.provider.test:
    container_name: build-acc.delivery.provider.test
    build: jenkins_buildnode
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    expose:
      - '50000'
    networks:
      delivery:
        ipv4_address: 172.16.12.4

  build-prod.delivery.provider.test:
    container_name: build-prod.delivery.provider.test
    build: jenkins_buildnode
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    expose:
      - '50000'
    networks:
      delivery:
        ipv4_address: 172.16.12.4
 
  portainer.monitoring.provider.test:
    container_name: portainer.monitoring.provider.test
    image: portainer/portainer-ce
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      tooling:
        ipv4_address: 172.16.13.3
    ports:
      - '9000:9000'
    healthcheck:
      test: curl --insecure --head --fail -s http://localhost || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  loki.monitoring.provider.test:
    container_name: loki.monitoring.provider.test
    build: loki
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    expose:
      - '3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      tooling:
        ipv4_address: 172.16.13.4

  promtail.monitoring.provider.test:
    container_name: promtail.monitoring.provider.test
    build: promtail
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      tooling:
        ipv4_address: 172.16.13.5

  grafana.monitoring.provider.test:
    container_name: grafana.monitoring.provider.test
    build: grafana
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - GF_SERVER_DOMAIN="grafana.monitoring.provider.test"
      - GF_SERVER_ROOT_URL="https://grafana.monitoring.provider.test"
      - GF_AUTH_GENERIC_OAUTH_ENABLED="true"
      - GF_AUTH_GENERIC_OAUTH_NAME="Login with Keycloak"
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP="false"
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID="grafana"
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET="$Grafana_CLIENT_SECRET"
      - GF_AUTH_GENERIC_OAUTH_SCOPES=profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL="https://keycloak.services.provider.test:8443/auth/realms/cicdtoolbox/protocol/openid-connect/auth"
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL="https://keycloak.services.provider.test:8443/auth/realms/cicdtoolbox/protocol/openid-connect/token"
      - GF_AUTH_GENERIC_OAUTH_API_URL="https://keycloak.services.provider.test:8443/auth/realms/cicdtoolbox/protocol/openid-connect/userinfo"
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH="contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"
    expose:
      - '3000'
    networks:
      tooling:
        ipv4_address: 172.16.13.6
