version: '3.7'
networks:
  tooling:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24
  
services:
  netcicd-db:
    container_name: netcicd-db
    build: netcicd-db
    restart: always
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - 'POSTGRES_MULTIPLE_DATABASES=gitea,keycloak'
      - POSTGRES_USER=netcicd
      - POSTGRES_PASSWORD=netcicd
    networks:
      tooling:
        ipv4_address: 172.16.11.2
    expose:
      - '5432'
    volumes:
      - './netcicd-db/db:/var/lib/postgresql/data'

  gitea:
    container_name: gitea
    build: gitea
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=gitea
      - SSH_DOMAIN=gitea
      - DB_TYPE=postgres
      - 'DB_HOST=netcicd-db:5432'
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - INSTALL_LOCK=true
      - SECRET_KEY=z5sRR3DQ4ZxJ5EcFSM8amg9eEfyLffxssDcO14bs2JlZRLwPl3E3PQ24xDMGB56j
      - REQUIRE_SIGNIN_VIEW=true
    networks:
      tooling:
        ipv4_address: 172.16.11.3
    volumes:
      - './gitea/data:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 3000:3000
    depends_on:
      - netcicd-db
      - keycloak
      
  jenkins:
    container_name: jenkins
    build: ./jenkins
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      tooling:
        ipv4_address: 172.16.11.8
    environment:
      - JENKINS_ADMIN_ID=jenkins_admin
      - JENKINS_ADMIN_PASSWORD=netcicd
      - NETCICD_PASSWORD=netcicd
      - CML_USER=developer
      - CML_PASSWORD=C1sco12345
      - 'CML_URL=https://10.10.20.161'
      - GIT_JENKINS_PASSWORD=netcicd
      - NEXUS_JENKINS_PASSWORD=netcicd
      - ARGOS_JENKINS_PASSWORD=netcicd
      - JENKINS_AGENT_CREATOR=netcicd
      - JENKINS_AGENT_CREATOR_KEY=somekey
    volumes:
      - './jenkins/keystore:/var/jenkins_home/keystore'
    ports:
      - 8084:8084
    depends_on:
      - keycloak

  nexus:
    container_name: nexus
    build: ./nexus
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    user: 'nexus'
    environment:
      BASE_URL: 'http://nexus:8081'
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
      NEXUS_CASC_CONFIG: '/opt/nexus.yaml'
    volumes:
      - './nexus/data:/sonatype-work'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      tooling:
        ipv4_address: 172.16.11.9
    ports:
      - 8081:8081

  mongodb:
    container_name: mongodb
    image: argosnotary/mongo:4.2.8
    networks:
      tooling:
        ipv4_address: 172.16.11.4
    expose:
      - '27017' 

  argos-frontend:
    container_name: argos
    image: argosnotary/argos-frontend:1.0.2
    environment:
      - BACKEND_URL=http://argos-service:8080
    networks:
      tooling:
        ipv4_address: 172.16.11.10
    ports:
      - 8082:80
    depends_on:
      - argos-service

  argos-service:
    container_name: argos-service
    image: argosnotary/argos-service:master-beta
    environment:
      spring.config.location: /application.yml
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      spring.profiles.active: integration-test
      JAVA_OPTS: '-Xmx1g'
    networks:
      tooling:
        ipv4_address: 172.16.11.5
    expose:
      - '8080'
    depends_on:
      - mongodb
      - keycloak
    volumes:
      - ./argos/application.yml:/application.yml

  keycloak:
    container_name: keycloak
    build: keycloak
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: netcicd-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      RADIUS_SHARED_SECRET: secret
      RADIUS_UDP: 'true'
      RADIUS_UDP_AUTH_PORT: 1812
      RADIUS_UDP_ACCOUNT_PORT: 1813
      RADIUS_RADSEC: 'false'
      RADIUS_RADSEC_PRIVATEKEY: /config/private.key
      RADIUS_RADSEC_CERTIFICATE: /config/public.crt
      RADIUS_COA: 'false'
      RADIUS_COA_PORT: 1700
    networks:
      tooling:
        ipv4_address: 172.16.11.11
    ports:
      - 8083:8080
      - 8443:8443
      - 1812:1812
      - 1813:1813
    depends_on:
      - netcicd-db

  nodered:
    container_name: nodered
    image: 'nodered/node-red:latest'
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - './nodered/data:/data'
    networks:
      tooling:
        ipv4_address: 172.16.11.13
    ports:
      - 1880:1880

  jupyter:
    container_name: jupyter
    image: jupyter/base-notebook
    restart: always
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - RESTARTABLE=yes
    volumes:
      - './jupyter/data/:/notebooks'
      - './jupyter/workspace:/home/jovyan'
    networks:
      tooling:
        ipv4_address: 172.16.11.14
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    volumes:
      - './portainer/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      tooling:
        ipv4_address: 172.16.11.15
    ports:
      - 9000:9000
