version: '3.7'
networks:
  tooling:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24
#  jumphosts:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.16.111.0/24
  reverse-proxy:

volumes:
  netcicd_db:
  freeipa:
  portainer_data:

services:
  netcicd-db:
    container_name: netcicd-db
    build: netcicd-db
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - 'POSTGRES_MULTIPLE_DATABASES=gitea,keycloak'
      - POSTGRES_USER=netcicd
      - POSTGRES_PASSWORD=netcicd
    networks:
      tooling:
        ipv4_address: 172.16.11.2
    expose:
      - '5432'
    volumes:
      - netcicd_db:/var/lib/postgresql/data

  gitea.tooling.test:
    container_name: gitea.tooling.test
    build: gitea
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=gitea
      - SSH_DOMAIN=gitea
      - DB_TYPE=postgres
      - 'DB_HOST=netcicd-db:5432'
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - INSTALL_LOCK=true
      - SECRET_KEY=z5sRR3DQ4ZxJ5EcFSM8amg9eEfyLffxssDcO14bs2JlZRLwPl3E3PQ24xDMGB56j
      - REQUIRE_SIGNIN_VIEW=true
    networks:
      tooling:
        ipv4_address: 172.16.11.3
    volumes:
      - './gitea/data:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '3000:3000'
    depends_on:
      - netcicd-db
      - keycloak.tooling.test

  jenkins.tooling.test:
    container_name: jenkins.tooling.test
    build: ./jenkins
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      tooling:
        ipv4_address: 172.16.11.8
    environment:
      - JENKINS_ADMIN_ID=jenkins_admin
      - JENKINS_ADMIN_PASSWORD=netcicd
      - NETCICD_PASSWORD=netcicd
      - CML_USER=developer
      - CML_PASSWORD=C1sco12345
      - 'CML_URL=https://10.10.20.161'
      - GITEA_IP=10.10.20.50
      - JENKINS_IP=10.10.20.50
      - NEXUS_IP=10.10.20.50
      - JENKINS_JENKINS_PASSWORD=netcicd
      - JENKINS_GIT_PASSWORD=netcicd
      - JENKINS_NEXUS_PASSWORD=netcicd
      - JENKINS_ARGOS_PASSWORD=netcicd
    volumes:
      - './jenkins/keystore:/var/jenkins_home/keystore'
    ports:
      - '8084:8084'
      - '50000:50000'
    depends_on:
      - keycloak.tooling.test

  nexus.tooling.test:
    container_name: nexus.tooling.test
    build: ./nexus
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    user: nexus
    environment:
      BASE_URL: 'http://nexus.tooling.test:8081'
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
      NEXUS_CASC_CONFIG: /opt/nexus.yaml
    volumes:
      - './nexus/data:/sonatype-work'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      tooling:
        ipv4_address: 172.16.11.9
    ports:
      - '8081:8081'

  keycloak.tooling.test:
    container_name: keycloak.tooling.test
    build: keycloak
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: netcicd-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    networks:
      tooling:
        ipv4_address: 172.16.11.11
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - netcicd-db

  freeipa.tooling.test:
    container_name: freeipa.tooling.test
    build: freeipa
    restart: unless-stopped
    hostname: freeipa
    domainname: tooling.test
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - freeipa:/data:Z 
    expose:
      - "80"
      - "443"
      - "389"
      - "636"
      - "88"
      - "464"
      - "88/udp"
      - "464/udp"
      - "123/udp"
    environment:
      - IPA_SERVER_HOSTNAME=freeipa.tooling.test
      - IPA_SERVER_INSTALL_OPTS=-d -r tooling.test --ntp-pool=pool.ntp.org --domain=tooling.test --reverse-zone=16.172.in-addr.arpa -p Pa55w0rd -a Pa55w0rd --no-host-dns --setup-dns --no-forwarders --ip-address 172.16.11.12 -U
      - IPA_SERVER_IP=172.16.11.12
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=freeipa.tooling.test
      - VIRTUAL_PORT=80
    dns:
      - 127.0.0.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      tooling:
        ipv4_address: 172.16.11.12
      reverse-proxy: 

  portainer.tooling.test:
    container_name: portainer.tooling.test
    image: portainer/portainer-ce
    restart: unless-stopped
    init: true
    stop_signal: SIGINT
    stop_grace_period: 15s
    volumes:
      - portainer_data:/data
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      tooling:
        ipv4_address: 172.16.11.15
    ports:
      - '9000:9000'

