#!/bin/bash 

local_admin_user="local-admin"
nexus_keycloak_plugin="0.5.0"
nexus_apk_plugin="0.0.23"
netcicd_pwd="netcicd"
keycloak_pwd="Pa55w0rd"
keycloak_storepass="password"
freeipa_pwd="Pa55w0rd"
jenkins_storepass="changeit"

echo "****************************************************************************************************************"
echo " Start clean" 
echo "****************************************************************************************************************"
docker-compose down --remove-orphans
docker volume rm $(docker volume ls -q)
rm *_token
rm install_tests/log.html
rm install_tests/output.xml
rm install_tests/report.html
rm install_tests/*.png
rm install_tests/*.log
rm install_log/*
echo " " 
echo "****************************************************************************************************************"
echo " Cleaning Gitea" 
echo "****************************************************************************************************************"
sudo rm -rf gitea/data/*
echo " " 
echo "****************************************************************************************************************"
echo " Cleaning Nexus" 
echo "****************************************************************************************************************"
sudo rm -rf nexus/data/*
sudo rm -rf nexus/*.kar
echo " " 
sudo chmod o+w /etc/hosts
if grep -q "gitea" /etc/hosts; then
    echo " Gitea exists in /etc/hosts, removing..."
    sudo sed -i '/gitea.tooling.test/d' /etc/hosts
fi
echo " Add Gitea to /etc/hosts"
sudo echo "172.16.11.3   gitea.tooling.test" >> /etc/hosts

if grep -q "jenkins" /etc/hosts; then
    echo " Jenkins exists in /etc/hosts, removing..."
    sudo sed -i '/jenkins.tooling.test/d' /etc/hosts
fi
echo " Add Jenkins to /etc/hosts"
sudo echo "172.16.11.8   jenkins.tooling.test" >> /etc/hosts

if grep -q "nexus" /etc/hosts; then
    echo " Nexus exists in /etc/hosts, removing..."
    sudo sed -i '/nexus.tooling.test/d' /etc/hosts
fi
echo " Add Nexus to /etc/hosts"
sudo echo "172.16.11.9   nexus.tooling.test" >> /etc/hosts

if grep -q "keycloak" /etc/hosts; then
    echo " Keycloak exists in /etc/hosts, removing..."
    sudo sed -i '/keycloak.tooling.test/d' /etc/hosts
fi
echo " Add Keycloak to /etc/hosts"
sudo echo "172.16.11.11   keycloak.tooling.test" >> /etc/hosts

if grep -q "freeipa" /etc/hosts; then
    echo " FreeIPA exists in /etc/hosts, removing..."
    sudo sed -i '/freeipa.tooling.test/d' /etc/hosts
fi
echo " Add FreeIPA to /etc/hosts"
sudo echo "172.16.11.12   freeipa.tooling.test" >> /etc/hosts

if grep -q "portainer" /etc/hosts; then
    echo " Portainer exists in /etc/hosts, removing..."
    sudo sed -i '/portainer.tooling.test/d' /etc/hosts
fi
echo " Add Portainer to /etc/hosts"
sudo echo "172.16.11.15   portainer.tooling.test" >> /etc/hosts

if grep -q "cml" /etc/hosts; then
    echo " Cisco Modeling Labs exists in /etc/hosts, removing..."
    sudo sed -i '/cml.tooling.test/d' /etc/hosts
fi
echo " Add Cisco Modeling Labs to /etc/hosts"
sudo echo "10.10.20.161   cml.tooling.test" >> /etc/hosts
sudo chmod o-w /etc/hosts
echo " " 
echo "****************************************************************************************************************"
echo " Collecting Nexus Keycloak plugin" 
echo "****************************************************************************************************************"
if [ -f "nexus/nexus3-keycloak-plugin-$nexus_keycloak_plugin-bundle.kar" ]; then
    echo " Nexus Keycloak plugin exists"
else
    echo " Get Nexus Keycloak plugin"
    wget --directory-prefix=nexus https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/v$nexus_keycloak_plugin/nexus3-keycloak-plugin-$nexus_keycloak_plugin-bundle.kar
fi
echo " " 
echo "****************************************************************************************************************"
echo " Making sure all containers are reachable locally with the name in the"
echo " hosts file."
echo " " 
echo "****************************************************************************************************************"
echo " Collecting Nexus APK plugin and build .kar file"
echo "****************************************************************************************************************"
if [ -f "nexus/nexus-repository-apk-$nexus_apk_plugin-bundle.kar" ]; then
    echo " Nexus apk plugin exists"
else
    echo " Get Nexus apk plugin"
    wget --directory-prefix=nexus https://search.maven.org/remotecontent?filepath=org/sonatype/nexus/plugins/nexus-repository-apk/$nexus_apk_plugin/nexus-repository-apk-$nexus_apk_plugin-bundle.kar
fi
echo " " 
echo "****************************************************************************************************************"
echo " git clone Nexus CasC plugin and build .kar file"
echo "****************************************************************************************************************"
if [ ! -f ./nexus/nexus-casc* ]; then
    git clone https://github.com/AdaptiveConsulting/nexus-casc-plugin.git
    cd nexus-casc-plugin
    mvn package
    cp target/*.kar ../nexus/
    cd ..
    rm -rf nexus-casc-plugin/
else
    echo "Casc plugin exists, no need to build"
fi
echo " " 
echo "****************************************************************************************************************"
echo " Creating database"
echo "****************************************************************************************************************"
docker-compose pull 
docker-compose up --build --remove-orphans --no-start 
docker-compose start netcicd-db
echo "****************************************************************************************************************"
echo " Calming down the CPU... waiting 10 seconds"
echo "****************************************************************************************************************"
sleep 10
docker-compose start freeipa.tooling.test
echo "****************************************************************************************************************"
echo " Wait until FreeIPA is running"
echo "****************************************************************************************************************"
until $(curl --output /dev/null --silent --head --fail --show-error http://freeipa.tooling.test); do
    printf 'Retrying.. \n'
    sleep 5
done
echo " "
echo "****************************************************************************************************************"
echo " Calming down the CPU ... waiting 20 seconds"
echo "****************************************************************************************************************"
sleep 20
echo " " 
echo "****************************************************************************************************************"
echo " Saving FreeIPA self-signed certificate"
echo "****************************************************************************************************************"
docker cp freeipa.tooling.test:/etc/ipa/ca.crt freeipa/ca.crt
echo " "
docker-compose start keycloak.tooling.test
echo "****************************************************************************************************************"
echo " Wait until keycloak is running"
echo "****************************************************************************************************************"
until $(curl --output /dev/null --silent --head --fail --show-error http://keycloak.tooling.test:8080); do
    printf 'Retrying.. \n'
    sleep 5
done
echo " "
echo "****************************************************************************************************************"
echo " Adding FreeIPA CA certificate to Keycloak"
echo "****************************************************************************************************************"
echo " "
docker cp freeipa/ca.crt keycloak.tooling.test:/opt/jboss/keycloak/standalone/configuration/keystores/freeipa-ca.crt
echo "****************************************************************************************************************"
echo " Creating keycloak setup. This will take time..."
echo "****************************************************************************************************************"
docker exec -it keycloak.tooling.test sh -c "/opt/jboss/keycloak/bin/create-realm.sh ${keycloak_pwd} ${keycloak_storepass} ${freeipa_pwd} ${local_admin_user}" | tee install_log/keycloak_create.log
echo " "
echo "****************************************************************************************************************"
echo " Creating FreeIPA setup. This will take time..."
echo "****************************************************************************************************************"
docker exec -it freeipa.tooling.test sh -c "/root/freeipa-install.sh ${netcicd_pwd} ${freeipa_pwd}" | tee install_log/freeipa_create.log
echo "****************************************************************************************************************"
echo " Restarting Keycloak "
echo "****************************************************************************************************************"
docker restart keycloak.tooling.test
echo "****************************************************************************************************************"
echo " Wait until keycloak is running"
echo "****************************************************************************************************************"
until $(curl --output /dev/null --silent --head --fail --show-error http://keycloak.tooling.test:8080); do
    printf 'Retrying.. \n'
    sleep 5
done
echo " "
echo "****************************************************************************************************************"
echo " Booting the remainder of the containers"
echo "****************************************************************************************************************"
docker-compose start
echo " "
echo "****************************************************************************************************************"
echo " Creating gitea setup"
echo "****************************************************************************************************************"
gitea/gitea_install.sh ${netcicd_pwd} ${local_admin_user} | tee install_log/gitea_create.log
echo " "
echo "****************************************************************************************************************"
echo " Creating jenkins setup"
echo "****************************************************************************************************************"
#config for oic_auth plugin: only need to replace secret in casc.yaml
jenkins_client_id=$(grep JENKINS_token: install_log/keycloak_create.log | cut -d' ' -f2 | tr -d '\r' )
docker exec -it jenkins.tooling.test sh -c "sed -i -e 's/oic_secret/\"$jenkins_client_id\"/' /var/jenkins_conf/casc.yaml"
echo "Reloading "
docker restart jenkins.tooling.test
echo " " 
echo " " 
echo "****************************************************************************************************************"
echo " Creating nexus setup"
echo "****************************************************************************************************************"
docker cp keycloak.tooling.test:/opt/jboss/keycloak/bin/keycloak-nexus.json nexus/keycloak-nexus.json
docker cp nexus/keycloak-nexus.json nexus.tooling.test:/opt/sonatype/nexus/etc/keycloak.json
echo "Reloading Nexus"
docker restart nexus.tooling.test
until $(curl --output /dev/null --silent --head --fail --show-error http://nexus.tooling.test:8081); do
    printf 'Retrying.. \n'
    sleep 5
done
echo " " 
echo "****************************************************************************************************************"
echo " Saving Keycloak self-signed certificate"
openssl s_client -showcerts -connect keycloak.tooling.test:8443 </dev/null 2>/dev/null|openssl x509 -outform PEM >./jenkins/keystore/keycloak.pem
echo " "
echo " Copy certificate into Jenkins keystore"
echo "****************************************************************************************************************"
docker cp jenkins.tooling.test:/opt/java/openjdk/lib/security/cacerts ./jenkins/keystore/cacerts
chmod +w ./jenkins/keystore/cacerts
keytool -import -alias Keycloak -keystore ./jenkins/keystore/cacerts -file ./jenkins/keystore/keycloak.pem -storepass ${jenkins_storepass} -noprompt
docker cp ./jenkins/keystore/cacerts jenkins.tooling.test:/opt/java/openjdk/lib/security/cacerts
echo "Reloading "
docker restart jenkins.tooling.test
until $(curl --output /dev/null --silent --head --fail --show-error http://jenkins.tooling.test:8084/whoAmI); do
    printf 'Retrying.. \n'
    sleep 5
done
echo " " 
echo "****************************************************************************************************************"
echo " Preparing for finalizing install via ROBOT"
echo "****************************************************************************************************************"
sudo pip3 install robotframework robotframework-selenium2library
sudo cp geckodriver /usr/local/bin/
source ~/.bashrc
robot --variable VALID_PASSWORD:${netcicd_pwd} -d install_log/ finalize_install.robot
robot --variable VALID_PASSWORD:${netcicd_pwd} -d install_tests/ install_tests
echo "****************************************************************************************************************"
echo " The pipeline uses the default Cisco DevNet CML Sandbox credentials developer/C1sco12345 to log in to CML."
echo " You may change this to your own credentials in:"
echo " "
echo " http://jenkins.tooling.test:8084/credentials/store/system/domain/_/credential/CML-SIM-CRED/update"
echo " "
echo " Due to limitations in Keycloak, do **not** use docker-compose down. Keycloak will no longer function after this."
echo " "
echo " Stop the environment with ./down, start with ./up"
echo " "
echo "****************************************************************************************************************"
echo "CICD Toolbox install done "
echo " "
echo "You can read the install test report in install_tests/report.html"
echo " "
echo "You can reach the servers on:"
echo " "
echo " Gitea:       http://gitea.tooling.test:3000"
echo " Jenkins:     http://jenkins.tooling.test:8084"
echo " Nexus:       http://nexus.tooling.test:8081"
echo " Keycloak:    http://keycloak.tooling.test:8443"
echo " FreeIPA:     http://freeipa.tooling.test"
echo " Portainer:   http://portainer.tooling.test:9000"
echo " "
echo "****************************************************************************************************************"
echo "Cleaning up"
echo "****************************************************************************************************************"
rm *_token
rm install_log/keycloak_create.log
