/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Some image
type Image struct {

	// Unique image ID
	Id int32 `json:"id,omitempty"`

	// Name of image
	Name string `json:"name"`

	// Description of Image
	Description string `json:"description,omitempty"`

	// Image type
	Type_ string `json:"type,omitempty"`

	// Image OS
	Os string `json:"os,omitempty"`

	// Status of image
	Status string `json:"status"`
}
