/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Contract in the datacenter
type Contract struct {

	// Unique contract ID
	Id int32 `json:"id,omitempty"`

	// Name of contract
	Name string `json:"name"`

	// Description of contract
	Description string `json:"description,omitempty"`

	// Costcenter of contract
	Costcenter string `json:"costcenter"`

	// Status of contract
	Status string `json:"status"`
}
