/*
 * Provider Portal
 *
 * This is the Swagger API voor an imaginary SP called Prov.
 *
 * API version: 0.0.1
 * Contact: automation@provider.test
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// AZ in the datacenter
type Az struct {

	// Unique az ID
	Id int32 `json:"id,omitempty"`

	// Name of az
	Name string `json:"name"`

	// Description of AZ
	Description string `json:"description,omitempty"`

	// Regio/cloud where the AZ is build
	Region string `json:"region,omitempty"`

	// Availability Zone waarin de AZ is gebuildd binnen de regio
	Az string `json:"az,omitempty"`

	// Name of the contract
	Party string `json:"party,omitempty"`

	// Status of az
	Status string `json:"status,omitempty"`
}
